args:
  IOHKaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
  IOHKroute53accessKeyId:
    tag: NixStr
    contents: iohkroot-cardano-deployer
  CFaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
  EmurgoaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
  systemStart:
    tag: NixInt
    contents: 1519242329
topology: topology-mainnet-infra.yaml
environment: Production
installer-bucket: stub
name: iohk-infra
files:
- deployments/keypairs.nix
- deployments/infrastructure.nix
- deployments/infrastructure-env-production.nix
- deployments/infrastructure-target-aws.nix
- deployments/packet-net.nix
elements:
- Infra
target: AWS
