deploymentName: staging
nixPath: nixpkgs=https://github.com/NixOS/nixpkgs/archive/9b948ea439ddbaa26740ce35543e7e35d2aa6d18.tar.gz
nixopsExecutable: nixops
deploymentFiles:
  - deployments/keypairs.nix
  - deployments/cardano-nodes.nix
  - deployments/cardano-nodes-env-staging.nix
  - deployments/cardano-nodes-target-aws.nix
  - deployments/cardano-explorer.nix
  - deployments/cardano-explorer-env-staging.nix
  - deployments/cardano-explorer-target-aws.nix
  - deployments/report-server.nix
  - deployments/report-server-env-staging.nix
  - deployments/report-server-target-aws.nix

