{
 "title": "Cardano: Application metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chain quality (Last k=2160 blocks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_chain_quality_last_k__2160__blocks__",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Quality Overall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_chain_quality_overall__",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Quality Last Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_chain_quality_last_3600_sec__",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Queue: Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_Failures", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Bucket Subscription Listener Counts (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_queue_bucket_BucketSubscriptionListener",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Queue: Scheduled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_Scheduled", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "MemPoolSize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_MemPoolSize", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "MemPool Wait Time (microseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_MemPoolWaitTimeApplyBlock_microseconds",
     "legendFormat": "{{alias}} - apply block"
    },
    {
     "expr": "cardano_MemPoolWaitTimeProcessTx_microseconds",
     "legendFormat": "{{alias}} - process tx"
    },
    {
     "expr": "cardano_MemPoolWaitTimeApplyBlockWithRollback_microseconds",
     "legendFormat": "{{alias}} - apply block with rollback"
    }
   ]
  },
  {
   "title": "MemPool Modify Time (microseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_MemPoolModifyTimeApplyBlock_microseconds",
     "legendFormat": "{{alias}} - apply block"
    },
    {
     "expr": "cardano_MemPoolModifyTimeProcessTx_microseconds",
     "legendFormat": "{{alias}} - process tx"
    },
    {
     "expr": "cardano_MemPoolModifyTimeApplyBlockWithRollback_microseconds",
     "legendFormat": "{{alias}} - apply block with rollback"
    }
   ]
  },
  {
   "title": "Number of blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_total_main_blocks", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_handlers_initiated_locally",
     "legendFormat": "{{alias}} - initiated locally"
    },
    {
     "expr": "cardano_handlers_initiated_remotely",
     "legendFormat": "{{alias}} - initiated remotely"
    }
   ]
  },
  {
   "title": "Handlers: Finished Exceptionally (sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_max / 1000000",
     "legendFormat": "{{alias}} - max"
    },
    {
     "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_mean / 1000000",
     "legendFormat": "{{alias}} - mean"
    }
   ]
  },
  {
   "title": "BucketSubscription (non-stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_queue_bucket_BucketSubscriptionListener",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "BucketSubscription (sum)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (cardano_queue_bucket_BucketSubscriptionListener)",
     "legendFormat": "sum all nodes"
    }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_current_global_slot - cardano_total_main_blocks",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}