{
 "title": "Cardano: Failure metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Failure counts by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (cardano_queue_FailedSend)", "legendFormat": "send" },
    {
     "expr": "sum (cardano_queue_FailedAllSends)",
     "legendFormat": "all sends"
    },
    {
     "expr": "sum (cardano_queue_FailedChooseAlt)",
     "legendFormat": "choose alt"
    },
    {
     "expr": "sum (cardano_queue_FailedEnqueueOne)",
     "legendFormat": "enqueue one"
    },
    {
     "expr": "sum(cardano_queue_FailedEnqueueAll)",
     "legendFormat": "enqueue all"
    },
    {
     "expr": "sum(cardano_queue_FailedCherishLoop)",
     "legendFormat": "cherish loop"
    }
   ]
  },
  {
   "title": "Failed Send",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_FailedSend", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Failed Choose Alt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_FailedChooseAlt", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Failed Enqueue All",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_FailedEnqueueAll", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Failed Enqueue One",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_queue_FailedEnqueueOne", "legendFormat": "{{alias}}" }
   ]
  }
 ]
}